### ISSUE TITLE
Probastats BA3 note typo found

### ISSUE THREAD

**Issue by jamsamjam** [JoachimFavre/UniversityNotes#16]
Hello,

on the page 38, I think a factorial is missing next to (r!)

![telegram-cloud-photo-size-4-5816832397369524678-x](https://github.com/user-attachments/assets/d0353da1-0156-4c21-9f74-a517acc5bb0d)

Thank you

**Comment by JoachimFavre** [comment]
Good eyes! Fixed in 16b9b4d266746116fbf17311ac20e381d68f06ce.
Thank you :)
